#cloud-config
hostname: "__HOSTNAME__" # Set the desired hostname
manage_etc_hosts: true # Ensure /etc/hosts is managed
disable_root: true # Disable root login
ssh_pwauth: __SSH_PWAUTH__ # Enable or disable SSH password authentication

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: __LOCK_PASSWD__
    # __PASSWORD_HASH__
    groups: users,adm,dialout,audio,netdev,video,plugdev,gpio,spi,i2c,render
    # __SSH_KEYS__

timezone: Etc/UTC

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  # Basics
  - curl # http client
  - git # git client
  # Networking troubleshooting & testing tools
  - bind9-dnsutils # for dig
  - iperf3 # for network performance testing
  - nmap # for network scanning
  - tcpdump # for packet capture & analysis
  # Performance / Health monitoring
  - htop # interactive process viewer
  - iftop # network bandwidth monitoring
  - stress-ng # CPU/RAM/IO stress testing
  # MQTT & BlinkStick (USB RGB LED controller) dependencies
  - python3-venv # for python venv (blinkstick)
  - mosquitto # MQTT broker
  - mosquitto-clients # mqtt pub/sub cli tools
  - libusb-1.0-0 # for blinkstick

apt:
  conf: |
    Acquire {
      Check-Date "false";
    };
